# Generated by Django 3.0.3 on 2020-02-12 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('role', models.CharField(max_length=20, verbose_name='role')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='code')),
                ('email', models.EmailField(max_length=40, verbose_name='email')),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2020, 2, 13, 7, 43, 9, 604031, tzinfo=utc), verbose_name='expires_at')),
            ],
        ),
    ]
