# Generated by Django 3.0.3 on 2020-02-15 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 6, 10, 52, 418469, tzinfo=utc), verbose_name='expires_at'),
        ),
    ]
